export const MOCK_LESSONS_LIST = [
  {
    id: 0,
    isStarred: true,
    isBookmarked: false,
    tag: 'Worksheets',
    title: 'Reading Comprehension - Rocks From Space',
    score: 4.2,
    certification: 'CEFR B1&B2',
    time: '20',
  },

  {
    id: 1,
    isStarred: false,
    isBookmarked: true,
    tag: 'Practice Questions',
    title: 'Reading Comprehension - Rocks From Space',
    score: 4.2,
    certification: 'CEFR B1&B2',
    time: '20',
  },

  {
    id: 2,
    isStarred: false,
    isBookmarked: false,
    tag: 'Practice Questions',
    title: 'Reading Comprehension - Rocks From Space',
    score: 4.2,
    certification: 'CEFR B1&B2',
    time: '20',
  },

  {
    id: 3,
    isStarred: false,
    isBookmarked: false,
    tag: 'Practice Questions',
    title: 'Reading Comprehension - Rocks From Space',
    score: 4.2,
    certification: 'CEFR B1&B2',
    time: '20',
  },
  {
    id: 4,
    isStarred: false,
    isBookmarked: false,
    tag: 'Practice Questions',
    title: 'Reading Comprehension - Rocks From Space',
    score: 4.2,
    certification: 'CEFR B1&B2',
    time: '20',
  },
  {
    id: 5,
    isStarred: false,
    isBookmarked: false,
    tag: 'Practice Questions',
    title: 'Reading Comprehension - Rocks From Space',
    score: 4.2,
    certification: 'CEFR B1&B2',
    time: '20',
  },
]
